name: Seed TODO Issues

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure labels exist
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: 'type: enhancement', color: 'a2eeef', description: 'New feature or request' },
              { name: 'area: ui', color: '1d76db', description: 'User interface related' },
              { name: 'area: content', color: '0e8a16', description: 'Text and content updates' },
              { name: 'area: seo', color: 'fbca04', description: 'SEO and metadata' },
            ];
            const { owner, repo } = context.repo;
            const existing = await github.paginate(github.rest.issues.listLabelsForRepo, { owner, repo, per_page: 100 });
            const existingNames = new Set(existing.map(l => l.name.toLowerCase()));
            for (const l of labels) {
              if (!existingNames.has(l.name.toLowerCase())) {
                await github.rest.issues.createLabel({ owner, repo, name: l.name, color: l.color, description: l.description });
              }
            }

      - name: Create issues
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issues = [
              {
                title: 'プロフィール/リンク更新',
                body: [
                  'フッターと連絡先のダミーリンクを実リンクに差し替え。',
                  '',
                  '- [ ] `src/app/layout.tsx` のフッター（X/GitHub/Email）',
                  '- [ ] `src/app/contact/page.tsx` の各リンク/表示名',
                ].join('\n'),
                labels: ['type: enhancement', 'area: content'],
              },
              {
                title: 'メタ情報の更新',
                body: [
                  'サイトのタイトル/説明などのメタデータを更新。',
                  '',
                  '- [ ] `src/app/layout.tsx` の `metadata.title`/`description`/`metadataBase`',
                ].join('\n'),
                labels: ['type: enhancement', 'area: seo'],
              },
              {
                title: 'OGP 画像と設定',
                body: [
                  'OGP 用の画像追加と Open Graph/Twitter 設定。',
                  '',
                  '- [ ] `src/app/og.png` を追加',
                  '- [ ] `src/app/layout.tsx` の `openGraph`/`twitter` を設定',
                ].join('\n'),
                labels: ['type: enhancement', 'area: seo'],
              },
              {
                title: 'サイトマップ/robots 追加',
                body: [
                  'サイトマップと robots を App Router で追加。',
                  '',
                  '- [ ] `src/app/sitemap.ts`',
                  '- [ ] `src/app/robots.ts`',
                ].join('\n'),
                labels: ['type: enhancement', 'area: seo'],
              },
              {
                title: 'Works の実データ化',
                body: [
                  'カードを実データから描画し、必要に応じて詳細ページ化。',
                  '',
                  '- [ ] `src/data/works.ts` を作成',
                  '- [ ] `src/app/works/page.tsx` でデータを使用',
                  '- [ ] 必要なら各詳細ページを作成',
                ].join('\n'),
                labels: ['type: enhancement', 'area: content'],
              },
              {
                title: 'Analytics の追加',
                body: [
                  '計測の追加（GA4 など）。',
                  '',
                  '- [ ] レイアウトに埋め込み or タグマネージャ連携',
                ].join('\n'),
                labels: ['type: enhancement'],
              },
              {
                title: 'テーマ切替の追加',
                body: [
                  'ダーク/ライトのテーマ切替を実装。',
                  '',
                  '- [ ] トグル実装と状態保持（`class` 制御）',
                ].join('\n'),
                labels: ['type: enhancement', 'area: ui'],
              },
              {
                title: 'カスタムドメイン設定',
                body: [
                  'カスタムドメイン利用時の設定。',
                  '',
                  '- [ ] `public/CNAME` を追加',
                  '- [ ] Pages 側でドメイン設定',
                ].join('\n'),
                labels: ['type: enhancement', 'area: content'],
              },
            ];
            for (const issue of issues) {
              await github.rest.issues.create({ owner, repo, title: issue.title, body: issue.body, labels: issue.labels });
            }

